---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "hubble-gke-exporter.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: hubble-ui
    {{- include "hubble-gke-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-ui
      {{- include "hubble-gke-exporter.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.ui.spec.podAnnotations }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}   
      labels:
        app.kubernetes.io/name: hubble-ui
        {{- with .Values.ui.spec.podLabels }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- include "hubble-gke-exporter.labels" . | nindent 8 }}
    spec:
      {{- with .Values.exporter.spec.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "hubble-gke-exporter.fullname" . }}-ui
      serviceAccountName: {{ include "hubble-gke-exporter.fullname" . }}-ui
      containers:
        - name: frontend
          image: "{{ .Values.ui.frontend.image.repository }}:{{ .Values.ui.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.ui.frontend.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            {{- with .Values.ui.frontend.spec.securityContext }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        - name: backend
          image: "{{ .Values.ui.backend.image.repository }}:{{ .Values.ui.backend.image.tag }}"
          imagePullPolicy: {{ .Values.ui.backend.image.imagePullPolicy }}
          env:
            - name: EVENTS_SERVER_PORT
              value: "8090"
            - name: FLOWS_API_ADDR
              value: "{{ include "hubble-gke-exporter.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.relay.port }}"
          ports:
            - name: grpc
              containerPort: 8090
          securityContext:
            {{- with .Values.ui.backend.spec.securityContext }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        - name: proxy
          image: "{{ .Values.ui.proxy.image.repository }}:{{ .Values.ui.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.ui.proxy.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8081
          command: 
            - envoy
          args:
            - -c
            - /etc/envoy.yaml
            - -l
            - info
          volumeMounts:
            - name: hubble-ui-envoy-yaml
              mountPath: /etc/envoy.yaml
              subPath: envoy.yaml
          securityContext:
            {{- with .Values.ui.proxy.spec.securityContext }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: hubble-ui-envoy-yaml
          configMap:
            name: {{ include "hubble-gke-exporter.fullname" . }}-envoy
