# Default values for hubble-gke-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
exporter:
  image:
    repository: docker.io/rueian/gke-hubble-export
    tag: latest
    imagePullPolicy: Always
  spec:
    hostNetwork: true
    tolerations:
      - operator: Exists
      - key: components.gke.io/gke-managed-components
        operator: Exists
    podLabels: {}
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}

ui:
  frontend:
    image:
      repository: quay.io/cilium/hubble-ui
      tag: v0.8.4
      imagePullPolicy: IfNotPresent
    spec:
      securityContext: {}
  backend:
    image:
      repository: quay.io/cilium/hubble-ui-backend
      tag: v0.8.4
      imagePullPolicy: IfNotPresent
    spec:
      securityContext: {}
  proxy:
    image:
      repository: docker.io/envoyproxy/envoy
      tag: v1.18.4
      imagePullPolicy: IfNotPresent
    spec:
      securityContext: {}
  spec:    
    replicas: 1
    podLabels: {}
    podAnnotations: {}
    podSecurityContext: {}

relay:
  image:
    repository: quay.io/cilium/hubble-relay
    imagePullPolicy: IfNotPresent
  spec:    
    replicas: 1
    podLabels: {}
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}

service:
  relay:
    type: ClusterIP
    port: 80
    name: http
  ui:
    type: ClusterIP
    port: 80
    name: http

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
